export const ERROR_CODES = {
  // 공통
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  // 인증
  DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  UNAUTHORIZED: 'UNAUTHORIZED',
  WRONG_CURRENT_PASSWORD: 'WRONG_CURRENT_PASSWORD',
  ALREADY_WITHDRAWN: 'ALREADY_WITHDRAWN',
  // 비밀번호
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  // 카테고리
  DUPLICATE_CATEGORY_NAME: 'DUPLICATE_CATEGORY_NAME',
  NAME_TOO_LONG: 'NAME_TOO_LONG',
  DEFAULT_CATEGORY_NOT_DELETABLE: 'DEFAULT_CATEGORY_NOT_DELETABLE',
  CATEGORY_HAS_TODOS: 'CATEGORY_HAS_TODOS',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  // 할일
  INVALID_DUE_DATE: 'INVALID_DUE_DATE',
  INVALID_TITLE: 'INVALID_TITLE',
  INVALID_CATEGORY: 'INVALID_CATEGORY',
  TODO_NOT_FOUND: 'TODO_NOT_FOUND',
  TODO_ALREADY_COMPLETED: 'TODO_ALREADY_COMPLETED',
  INVALID_DATE_FORMAT: 'INVALID_DATE_FORMAT',
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
